# Generated by Django 5.2.7 on 2025-11-06 21:47

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('endereco', models.TextField()),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.URLField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('plano', models.CharField(default='BASIC', max_length=20)),
                ('asaas_api_key', models.CharField(blank=True, max_length=200)),
                ('asaas_wallet_id', models.CharField(blank=True, max_length=100)),
                ('exigir_2fa', models.BooleanField(default=False)),
                ('tempo_sessao_horas', models.IntegerField(default=8)),
                ('max_tentativas_login', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escolas',
                'db_table': 'escolas',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('SUPERUSER', 'Super Usuário'), ('GESTOR', 'Gestor'), ('COORDENADOR', 'Coordenador'), ('PROFESSOR', 'Professor'), ('RESPONSAVEL', 'Responsável'), ('ALUNO', 'Aluno')], max_length=20)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('foto', models.URLField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('ativo', models.BooleanField(default=True)),
                ('email_verificado', models.BooleanField(default=False)),
                ('primeiro_acesso', models.BooleanField(default=True)),
                ('senha_temporaria', models.BooleanField(default=False)),
                ('tentativas_login_falhas', models.IntegerField(default=0)),
                ('bloqueado_ate', models.DateTimeField(blank=True, null=True)),
                ('ultimo_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_criados', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, related_name='sophia_users', related_query_name='sophia_user', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='sophia_users', related_query_name='sophia_user', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('data_nascimento', models.DateField()),
                ('turno', models.CharField(blank=True, choices=[('MATUTINO', 'Matutino'), ('VESPERTINO', 'Vespertino'), ('NOTURNO', 'Noturno'), ('INTEGRAL', 'Integral')], max_length=20)),
                ('cpf', models.CharField(blank=True, max_length=14)),
                ('rg', models.CharField(blank=True, max_length=20)),
                ('endereco', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('TRANSFERIDO', 'Transferido'), ('CONCLUIDO', 'Concluído')], default='ATIVO', max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aluno_profile', to=settings.AUTH_USER_MODEL)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='sophia.escola')),
            ],
            options={
                'db_table': 'alunos',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=20)),
                ('carga_horaria', models.IntegerField(help_text='Horas por semana')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='sophia.escola')),
            ],
            options={
                'db_table': 'disciplinas',
            },
        ),
        migrations.CreateModel(
            name='AnoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anos_letivos', to='sophia.escola')),
            ],
            options={
                'db_table': 'anos_letivos',
                'unique_together': {('escola', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mensagem', models.TextField()),
                ('anexos', models.JSONField(blank=True, default=list)),
                ('lida', models.BooleanField(default=False)),
                ('enviada_em', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to=settings.AUTH_USER_MODEL)),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mensagens',
                'ordering': ['enviada_em'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoAvaliativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('ordem', models.IntegerField()),
                ('ano_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='sophia.anoletivo')),
            ],
            options={
                'db_table': 'periodos_avaliativos',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registro_profissional', models.CharField(blank=True, max_length=50)),
                ('formacao', models.CharField(max_length=200)),
                ('especializacao', models.CharField(blank=True, max_length=200)),
                ('data_admissao', models.DateField()),
                ('carga_horaria', models.IntegerField(default=40)),
                ('turno', models.CharField(choices=[('MATUTINO', 'Matutino'), ('VESPERTINO', 'Vespertino'), ('NOTURNO', 'Noturno'), ('INTEGRAL', 'Integral')], max_length=20)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('FERIAS', 'Férias'), ('LICENCA', 'Licença'), ('AFASTADO', 'Afastado')], default='ATIVO', max_length=20)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professores', to='sophia.escola')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'db_table': 'professores',
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('parentesco', models.CharField(max_length=50)),
                ('profissao', models.CharField(blank=True, max_length=100)),
                ('endereco', models.TextField(blank=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'responsaveis',
            },
        ),
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('competencia', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('BOLETO', 'Boleto'), ('PIX', 'PIX'), ('CARTAO', 'Cartão de Crédito'), ('DINHEIRO', 'Dinheiro')], max_length=20)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('asaas_payment_id', models.CharField(blank=True, max_length=100)),
                ('boleto_url', models.URLField(blank=True)),
                ('pix_qrcode', models.TextField(blank=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensalidades', to='sophia.aluno')),
                ('responsavel_financeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensalidades', to='sophia.responsavel')),
            ],
            options={
                'db_table': 'mensalidades',
            },
        ),
        migrations.CreateModel(
            name='SessaoUsuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=500, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('ultimo_acesso', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sessoes_usuarios',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TokenRedefinicaoSenha',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('usado', models.BooleanField(default=False)),
                ('expira_em', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_senha', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tokens_redefinicao_senha',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=50)),
                ('turno', models.CharField(choices=[('MATUTINO', 'Matutino'), ('VESPERTINO', 'Vespertino'), ('NOTURNO', 'Noturno'), ('INTEGRAL', 'Integral')], max_length=20)),
                ('capacidade_maxima', models.IntegerField(default=30)),
                ('sala', models.CharField(max_length=20)),
                ('ano_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='sophia.anoletivo')),
                ('coordenador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_coordenadas', to=settings.AUTH_USER_MODEL)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='sophia.escola')),
                ('professor_titular', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_tituladas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'turmas',
                'unique_together': {('escola', 'ano_letivo', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('REUNIAO', 'Reunião'), ('PROVA', 'Prova'), ('EVENTO', 'Evento'), ('FERIADO', 'Feriado'), ('ADMINISTRATIVO', 'Administrativo'), ('CULTURAL', 'Cultural'), ('ESPORTIVO', 'Esportivo')], max_length=20)),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('local', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('participantes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('AGENDADO', 'Agendado'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado'), ('REALIZADO', 'Realizado')], default='AGENDADO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='sophia.escola')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_responsavel', to=settings.AUTH_USER_MODEL)),
                ('turmas', models.ManyToManyField(blank=True, related_name='eventos', to='sophia.turma')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'eventos',
                'ordering': ['-data', '-hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('anexos', models.JSONField(blank=True, default=list)),
                ('enviar_para_todos', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_criados', to=settings.AUTH_USER_MODEL)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='sophia.escola')),
                ('turmas', models.ManyToManyField(blank=True, related_name='avisos', to='sophia.turma')),
            ],
            options={
                'db_table': 'avisos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma_atual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='sophia.turma'),
        ),
        migrations.CreateModel(
            name='TurmaDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sophia.disciplina')),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinas_lecionadas', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='sophia.turma')),
            ],
            options={
                'db_table': 'turma_disciplinas',
                'unique_together': {('turma', 'disciplina')},
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tipo_avaliacao', models.CharField(max_length=50)),
                ('data_avaliacao', models.DateField()),
                ('observacao', models.TextField(blank=True)),
                ('lancado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='sophia.aluno')),
                ('lancado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='sophia.periodoavaliativo')),
                ('turma_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='sophia.turmadisciplina')),
            ],
            options={
                'db_table': 'notas',
            },
        ),
        migrations.CreateModel(
            name='AtividadeAgenda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('LICAO', 'Lição de Casa'), ('TRABALHO', 'Trabalho'), ('PROVA', 'Prova'), ('PROJETO', 'Projeto')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('anexos', models.JSONField(blank=True, default=list)),
                ('data_entrega', models.DateField()),
                ('nota_maxima', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_criadas', to=settings.AUTH_USER_MODEL)),
                ('turma_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='sophia.turmadisciplina')),
            ],
            options={
                'db_table': 'atividades_agenda',
            },
        ),
        migrations.CreateModel(
            name='EscolaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_na_escola', models.CharField(max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('data_vinculo', models.DateTimeField(auto_now_add=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_vinculados', to='sophia.escola')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escolas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vínculo Escola-Usuário',
                'verbose_name_plural': 'Vínculos Escola-Usuário',
                'db_table': 'escola_usuarios',
                'unique_together': {('escola', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='HistoricoLogin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sucesso', models.BooleanField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=100)),
                ('pais', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_logins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historico_logins',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['usuario', '-timestamp'], name='historico_l_usuario_4f85c0_idx'), models.Index(fields=['ip_address'], name='historico_l_ip_addr_d6707f_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlunoResponsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel_financeiro', models.BooleanField(default=False)),
                ('prioridade', models.IntegerField(default=1)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to='sophia.aluno')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='sophia.responsavel')),
            ],
            options={
                'db_table': 'aluno_responsaveis',
                'unique_together': {('aluno', 'responsavel')},
            },
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('presente', models.BooleanField(default=True)),
                ('justificativa', models.TextField(blank=True)),
                ('lancado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='sophia.aluno')),
                ('lancado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('turma_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='sophia.turmadisciplina')),
            ],
            options={
                'db_table': 'frequencias',
                'unique_together': {('aluno', 'turma_disciplina', 'data')},
            },
        ),
    ]
