# Generated by Django 5.2.7 on 2025-11-10 18:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sophia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalComunicacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GRUPO_TURMA', 'Grupo de Turma'), ('GRUPO_DISCIPLINA', 'Grupo de Disciplina'), ('GRUPO_PROJETO', 'Grupo de Projeto'), ('OFICIAL', 'Canal Oficial')], max_length=20)),
                ('nome', models.CharField(blank=True, max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('visivel_para_gestao', models.BooleanField(default=True)),
                ('visivel_para_coordenacao', models.BooleanField(default=True)),
                ('permite_anexos', models.BooleanField(default=True)),
                ('permite_entrega_trabalhos', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('ARQUIVADO', 'Arquivado'), ('BLOQUEADO', 'Bloqueado')], default='ATIVO', max_length=20)),
                ('fixado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ultima_mensagem_em', models.DateTimeField(blank=True, null=True)),
                ('administradores', models.ManyToManyField(blank=True, related_name='canais_administrados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canais_criados', to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canais', to='sophia.disciplina')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canais', to='sophia.escola')),
                ('silenciado_por', models.ManyToManyField(blank=True, related_name='canais_silenciados', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canais', to='sophia.turma')),
            ],
            options={
                'verbose_name': 'Canal de Comunicação',
                'verbose_name_plural': 'Canais de Comunicação',
                'db_table': 'canais_comunicacao',
                'ordering': ['-fixado', '-ultima_mensagem_em'],
            },
        ),
        migrations.CreateModel(
            name='MensagemCanal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('TEXTO', 'Texto'), ('ARQUIVO', 'Arquivo'), ('TRABALHO', 'Entrega de Trabalho'), ('AVISO', 'Aviso'), ('SISTEMA', 'Mensagem do Sistema')], default='TEXTO', max_length=20)),
                ('conteudo', models.TextField()),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=20)),
                ('editada', models.BooleanField(default=False)),
                ('editada_em', models.DateTimeField(blank=True, null=True)),
                ('excluida', models.BooleanField(default=False)),
                ('excluida_em', models.DateTimeField(blank=True, null=True)),
                ('lida', models.BooleanField(default=False)),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
                ('visualizacoes', models.IntegerField(default=0)),
                ('ip_remetente', models.GenericIPAddressField(blank=True, null=True)),
                ('enviada_em', models.DateTimeField(auto_now_add=True)),
                ('requer_confirmacao', models.BooleanField(default=False)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='sophia.canalcomunicacao')),
                ('confirmada_por', models.ManyToManyField(blank=True, related_name='mensagens_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('remetente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_canal_enviadas', to=settings.AUTH_USER_MODEL)),
                ('respondendo_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas', to='sophia.mensagemcanal')),
            ],
            options={
                'db_table': 'mensagens_canal',
                'ordering': ['enviada_em'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaConversa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acao', models.CharField(choices=[('MENSAGEM_ENVIADA', 'Mensagem Enviada'), ('MENSAGEM_EDITADA', 'Mensagem Editada'), ('MENSAGEM_EXCLUIDA', 'Mensagem Excluída'), ('CANAL_CRIADO', 'Canal Criado'), ('PARTICIPANTE_ADICIONADO', 'Participante Adicionado'), ('PARTICIPANTE_REMOVIDO', 'Participante Removido'), ('CONVERSA_ASSUMIDA', 'Conversa Assumida'), ('CONVERSA_DEVOLVIDA', 'Conversa Devolvida'), ('ARQUIVO_ENVIADO', 'Arquivo Enviado'), ('TRABALHO_ENTREGUE', 'Trabalho Entregue')], max_length=30)),
                ('detalhes', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='sophia.canalcomunicacao')),
                ('mensagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sophia.mensagemcanal')),
            ],
            options={
                'db_table': 'auditoria_conversa',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AnexoMensagem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('IMAGEM', 'Imagem'), ('DOCUMENTO', 'Documento'), ('VIDEO', 'Vídeo'), ('AUDIO', 'Áudio'), ('OUTRO', 'Outro')], max_length=20)),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('tamanho', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('e_trabalho', models.BooleanField(default=False)),
                ('nota_trabalho', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('feedback_professor', models.TextField(blank=True)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('downloads', models.IntegerField(default=0)),
                ('atividade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sophia.atividadeagenda')),
                ('mensagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='sophia.mensagemcanal')),
            ],
            options={
                'db_table': 'anexos_mensagem',
                'ordering': ['enviado_em'],
            },
        ),
        migrations.CreateModel(
            name='NotificacaoComunicacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('NOVA_MENSAGEM', 'Nova Mensagem'), ('MENCAO', 'Menção'), ('RESPOSTA', 'Resposta'), ('TRABALHO_ENTREGUE', 'Trabalho Entregue'), ('CONVERSA_ASSUMIDA', 'Conversa Assumida'), ('SLA_ALERTA', 'Alerta de SLA'), ('CANAL_CRIADO', 'Canal Criado')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
                ('enviada_por_email', models.BooleanField(default=False)),
                ('enviada_por_sms', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='sophia.canalcomunicacao')),
                ('mensagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sophia.mensagemcanal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_comunicacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificacoes_comunicacao',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='ParticipanteCanal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('papel', models.CharField(choices=[('MEMBRO', 'Membro'), ('MODERADOR', 'Moderador'), ('ADMIN', 'Administrador')], default='MEMBRO', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('pode_enviar', models.BooleanField(default=True)),
                ('pode_ver_historico', models.BooleanField(default=True)),
                ('notificar', models.BooleanField(default=True)),
                ('notificar_email', models.BooleanField(default=False)),
                ('notificar_sms', models.BooleanField(default=False)),
                ('adicionado_em', models.DateTimeField(auto_now_add=True)),
                ('ultima_visualizacao', models.DateTimeField(auto_now=True)),
                ('adicionado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_adicionados', to=settings.AUTH_USER_MODEL)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='sophia.canalcomunicacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes_canais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'participantes_canal',
                'ordering': ['papel', 'usuario__first_name'],
            },
        ),
        migrations.CreateModel(
            name='ResponsavelConversa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assumida_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_assuncao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('devolvida', models.BooleanField(default=False)),
                ('devolvida_em', models.DateTimeField(blank=True, null=True)),
                ('prazo_resposta', models.IntegerField(default=24, help_text='Horas para responder')),
                ('alertado', models.BooleanField(default=False)),
                ('atrasado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('assumida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversas_assumidas', to=settings.AUTH_USER_MODEL)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to='sophia.canalcomunicacao')),
                ('responsavel_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas_originais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'responsavel_conversa',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Visualizacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visualizada_em', models.DateTimeField(auto_now_add=True)),
                ('mensagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes_detalhadas', to='sophia.mensagemcanal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_visualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'visualizacoes_mensagem',
                'ordering': ['-visualizada_em'],
            },
        ),
        migrations.AddIndex(
            model_name='mensagemcanal',
            index=models.Index(fields=['canal', '-enviada_em'], name='mensagens_c_canal_i_1cc716_idx'),
        ),
        migrations.AddIndex(
            model_name='mensagemcanal',
            index=models.Index(fields=['remetente', '-enviada_em'], name='mensagens_c_remeten_4fb8fc_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaconversa',
            index=models.Index(fields=['canal', '-criado_em'], name='auditoria_c_canal_i_1d8fe2_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaconversa',
            index=models.Index(fields=['usuario', '-criado_em'], name='auditoria_c_usuario_7839c0_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacaocomunicacao',
            index=models.Index(fields=['usuario', 'lida', '-criada_em'], name='notificacoe_usuario_5b23b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='participantecanal',
            unique_together={('canal', 'usuario')},
        ),
        migrations.AlterUniqueTogether(
            name='visualizacao',
            unique_together={('mensagem', 'usuario')},
        ),
    ]
